---
  - hosts: centos
    tasks:
      - debug:
          msg: "Yo no me voy a ejecutar ... :( ..."
        tags: 
        - no-exec
      - debug:
          msg: "Yo si me voy a ejecutar ... :) ... "
        tags: 
        - si-exec